---
title: "Plots"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=F}
library(tikzDevice)
library(magrittr)
library(knitr)
library(data.table)
library(ggplot2)
library(shiny)
library(shinythemes)
library(dplyr)
library(readr)
library(mvtnorm)
library(VGAM)
library(sampleSelection)
library(rootSolve)
library(plotly)

opts_chunk$set(#dev='tikz', 
               fig.path='./figure/', 
               echo=F, error=F, cache=F, message=F, warning=F,
               # results='hide', 
               autodep=T,
               fig.height = 6)

options(stringsAsFactors = F)


par(mar = c(0.5,0.5,0,0), oma = c(1,1,1,0), mgp = c(0.5, 0, 0), cex.axis=.9, cex = 2)
```

```{r parameters, include=F}
# success premiums
alphas = c(0.2, 0.2) # agent 1 or 2

# coumpound rates
rs = c(0.01, 0.01) # agent 1 or 2

mu = 0.002
sigma = 0.1
taua = 3
taub = 4
taueps = 1
pt1 = 2 #current price is given, but strike price is to be negotiated

P0s = seq(0.18,3,length.out = 999)

# universal upper boundary of alpha
alphaupper = 1

# universal lower boundary of alpha
alphalower = 0 # -1
```

```{r functions, include=F}
# Utility function
util = function(Price, Time, Suc, agent){
  (1+alphas[agent]*Suc)*Price/exp(rs[agent]*Time)
}

# Brownian motion PDF
gbmpdf = function(x, Price, Time){
  exp(-(
   2 * log(x/Price) - (2*mu-sigma^2)*Time
  )^2/(8*sigma^2*Time)
  )/(
    sqrt(2*pi*Time)*x*sigma
    )
}

# Brownian motion CDF
gbmcdf = function(x, Price, Time){
  erfc( # complementary error function erfc
    (log(Price/x)+(mu-sigma^2/2)*Time)/(sqrt(2*Time)*sigma)
    )/2
}

```

```{r basic, include=F}
# Price = 2
# Time = 2
# x = seq(0, 4, 0.01)
# plot(x, gbmpdf(x, Price, Time), type = 'l') # checked with mathematica
# plot(x, gbmcdf(x, Price, Time), type = 'l') # checked with mathematica

# price lower bound for Alice to continue at t3
P3l = function(P0, alpha){
  P0/(
  (1+alpha)*exp((mu-rs[1])*taub+rs[1]*(taua+taueps))
)
}

## unitily of Alice at t_3 if continue, Alice gets 1 at t_3+taub if P_3 > P_3 lowerbound
util2Acont = function(pt3vs){util(
  pt3vs*exp(mu*taub), taub, 1, 1
  )}

## utility of Alice at t_3 if withdraw, Alice gets P0 at t_3+taua+taueps
util2Astop = function(P0){
  util(P0, taua+taueps, 0, 1)
}

## expected utility of Alice at t_3 given t_2
util2A = function(pt2, P0, alpha=alphas[1]){
  pt3threshv = P3l(P0, alpha)
  temp = function(pt3){
    gbmpdf(pt3, pt2, taub) * util2Acont(pt3)
  }
  gbmcdf(pt3threshv, pt2, taub) * util2Astop(P0) + integrate(temp, pt3threshv, Inf, abs.tol = 0)$value
}


# expected utility for Bob if continue
utilBcont = function(x, P0){
  # probability to be lower than lower bound 
  p = gbmcdf(P3l(P0, alphas[1]), x, taub)
  (1-p)*util(
    P0,taua+taueps,1,2
    ) + p*util(
      x*exp(2*mu*taub), 2*taub, 0, 2
      )
}

## for Bob, how much does continue utility exceed waive
contlessstopB = function(x, P0){
    utilBcont(x, P0) - x
}

P2thresh = function(P0){
  tempfunc = function(x){contlessstopB(x, P0)}
  uniroot.all(tempfunc, lower = 0.01, upper = 999, maxiter = 99999, n = 9999)
}


## Utility of Alice at t_1 if continue
util1Acont = function(P0){
  
  temp = function(pt2){
    gbmpdf(pt2, pt1, taua) * util2A(pt2, P0)
  }
  pt2threshv = P2thresh(P0)
  
  # Alice's utility at t3 if Bob continues, gives terribly wrong answer if omitting abs.tol
  utilt3 = integrate(Vectorize(temp), pt2threshv[1], pt2threshv[2], abs.tol = 0)$value
  
  probBobwaive = 1-gbmcdf(pt2threshv[2], P0, taua) + gbmcdf(pt2threshv[1], P0, taua)
  utilt3/exp(rs[1]*(taua+taub)) + probBobwaive*P0/exp(rs[1]*(2*taua+taub))
}


sucrate = function(P0){
  pt3threshv = P3l(P0, alphas[1])
  temp = function(pt2){
    gbmpdf(pt2, pt1, taua) * (1-gbmcdf(pt3threshv, pt2, taub))
  }
  pt2threshv = P2thresh(P0)
  
  # gives terribly wrong answer if omitting abs.tol
  integrate(Vectorize(temp), pt2threshv[1], pt2threshv[2]
            # , abs.tol = 0
            )$value
}

```

```{r collateral, include=F}
# Utility function with collateral
util_col = function(Price, Time, Suc, agent, Col, tc){
  (1+alphas[agent]*Suc)*Price/exp(rs[agent]*Time) +
    Col/exp(rs[agent]*tc)
}

# price lower bound for Alice to continue at t3
P3l_col = function(P0, alpha){
  pmax(
    P0/exp(rs[1]*(taua+taueps)) - collat[1]/exp(taua*rs[1]),
    0
  ) * exp((rs[1]-mu)*taub)/(1+alpha)
}

## unitily of Alice at t_3 if continue, Alice gets 1 at t_3+taub and C_A at t_3+tau_a, if P_3 > P_3 lowerbound
util2Acont_col = function(pt3vs){util_col(
  pt3vs*exp(mu*taub), taub, 1, 1, collat[1], taua
  )}

## utility of Alice at t_3 if withdraw, Alice gets P0 at t_3+taua+taueps
# util2Astop = function(P0){
#   util(P0, taua+taueps, 0, 1)
# } ## already defined above


## expected utility of Alice at t_3 given t_2
util2A_col = function(pt2, P0, alpha=alphas[1]){
  pt3threshv = P3l_col(P0, alpha)
  temp = function(pt3){
    gbmpdf(pt3, pt2, taub) * util2Acont_col(pt3)
  }
  # here with Inf, R won't evaluate, so just do 15
  gbmcdf(pt3threshv, pt2, taub) * util2Astop(P0) + integrate(temp, pt3threshv, Inf)$value
}


# expected utility for Bob if continue
utilBcont_col = function(x, P0){
  # probability to be lower than lower bound 
  p = gbmcdf(P3l(P0, alphas[1]), x, taub)
  collat[2]/exp(rs[2] * taua) +
  (1-p)*util(
    P0,taua+taueps,1,2
    ) + p*util_col(
      x*exp(2*mu*taub), 2*taub, 0, 2, collat[1], taub+taua
      )
}

## for Bob, how much does continue utility exceed waive
contlessstopB_col = function(x, P0){
    utilBcont_col(x, P0) - x
}

P2thresh_col = function(P0){
  tempfunc = function(x){
    utilBcont_col(x, P0) - x
    }
  uniroot.all(tempfunc, lower = 0.001, upper = 999, maxiter = 99999, n = 9999)
}
## Note that there can be 3 roots!!!

## Utility of Alice at t_1 if continue
util1Acont_col = function(P0){
  
  temp = function(pt2){
    gbmpdf(pt2, pt1, taua) * util2A_col(pt2, P0)
  }
  pt2threshv = P2thresh_col(P0)
  
  
  if (length(pt2threshv) != 2){
  pt2threshv = union(0.0001, pt2threshv)
  }
  
  # pt2threshv = c(0, pt2threshv)
  
  utilt3  = 0
  
  probBobcont = 0
  
  # integrate over all sets that make U_continue > U_waive
  for (bound_ind in seq(1, length(pt2threshv), by = 2)){
    # Alice's utility at t3 if Bob continues, gives terribly wrong answer if omitting abs.tol
  utilt3 = utilt3 + integrate(
    Vectorize(temp), pt2threshv[bound_ind], pt2threshv[bound_ind+1], abs.tol = 0
    )$value
  probBobcont = probBobcont + (
    gbmcdf(pt2threshv[bound_ind+1], P0, taua) - gbmcdf(pt2threshv[bound_ind], P0, taua)
    )
  }
  
  probBobwaive = 1-probBobcont
  utilt3/exp(rs[1]*(taua+taub)) + 
    probBobwaive*(
      P0/exp(rs[1]*(2*taua+taub)) + (collat[1] + collat[2])/exp(rs[1]*2*taua)
    )
}


## Utility of Bob at t_1 if continue
util1Bcont_col = function(P0){
   
  temp = function(pt2){
    gbmpdf(pt2, pt1, taua) * pmax(utilBcont_col(pt2, P0), pt2)
  }
  integrate(
    Vectorize(temp), 0, Inf, abs.tol = 0
    )$value
  # pt2threshv = P2thresh_col(P0)
  # 
  # 
  # if (length(pt2threshv) != 2){
  # pt2threshv = union(0.0001, pt2threshv)
  # }
  # 
  # # utilt2B  = 0
  # 
  # probBobcont = 0
  
  # integrate over all sets that make U_continue > U_waive
  # for (bound_ind in seq(1, length(pt2threshv), by = 2)){
  #   # Bob's utility at t2, gives terribly wrong answer if omitting abs.tol
  # utilt3 = utilt3 + integrate(
  #   Vectorize(temp), pt2threshv[bound_ind], pt2threshv[bound_ind+1], abs.tol = 0
  #   )$value
  # probBobcont = probBobcont + (
  #   gbmcdf(pt2threshv[bound_ind+1], P0, taua) - gbmcdf(pt2threshv[bound_ind], P0, taua)
  #   )
  # }
  # 
  # probBobwaive = 1-probBobcont
  # utilt3/exp(rs[1]*(taua+taub)) + 
  #   probBobwaive*(
  #     P0/exp(rs[1]*(2*taua+taub)) + (collat[1] + collat[2])/exp(rs[1]*2*taua)
  #   )
}



sucrate_col = function(P0){
  pt3threshv = P3l_col(P0, alphas[1])
  
  pt2threshv = P2thresh_col(P0)
    
  if (length(pt2threshv) != 2){
    # R can't handle  gbmpdf(0, pt1, taua), so pt2 has to be slightly above 0
  pt2threshv = union(0.0001, pt2threshv)
  }
  
  temp = function(pt2){
    gbmpdf(pt2, pt1, taua) * (1-gbmcdf(pt3threshv, pt2, taub))
  }
  
  # integrate over all sets that make U_continue > U_waive
  p = 0
  for (bound_ind in seq(1, length(pt2threshv), by = 2)){
  # gives terribly wrong answer if omitting abs.tol
  p = p + integrate(
    Vectorize(temp), pt2threshv[bound_ind], pt2threshv[bound_ind+1]
    # , abs.tol = 0
    )$value
  }
  return(p)
}
```

```{r uncertain, include=F}

## now if type is uncertain

# uncertain utility function is used when one agent is calculating the other agent's utility, where the other agent's alpha is unknown
# when one agent is calculating its own utility, use `util`, or specify alpha = alphas[agent]
utilunc = function(Price, Time, Suc, agent, alpha){
  (1+alpha*Suc)*Price/exp(rs[agent]*Time)
}

## expected utility for Bob if continue, uncertain about alpha^A, but alpha^A lower bound is known
utilBcontunc = function(x, P0, alphalower, alphaB){
  temp = function(alphaA){
  # probability to be lower than lower bound 
  p = gbmcdf(P3l(P0, alphaA), x, taub)
  (1-p)*utilunc(
    P0, taua+taueps, 1, 2, alphaB
    )+p*utilunc(
      x*exp(2*mu*taub), 2*taub, 0, 2, alphaB
    )
  }
  
  integrate(Vectorize(temp), alphalower, 1, abs.tol = 0)$value / (1-alphalower)
}

contlessstopBunc = function(x, P0, alphalower, alphaB){
utilBcontunc(x, P0, alphalower, alphaB)- x
}


# Higher alphaB should relax the feasible range of P_2. Note that when alphaB is too small, maybe no P_2 will make Bob trade. The borderline alphaB should lead to one feasible P_2 point
P2threshunc = function(P0, alphalower, alphaB){
  tempfunc = function(x){contlessstopBunc(x, P0, alphalower, alphaB)
    }
  
  # if not vectorize: evaluation of function gave a result of wrong length
  uniroot.all(Vectorize(tempfunc), lower = 0.001, upper = 999, maxiter = 99999, n = 9999)
}

## expected utility of Alice at t_3 given t_2

# # Bob estimates its utility given alpha^A's lower boundary
# util2Aunc = function(pt2, P0, alphalower){
#   temp0 = function(alpha){
#   pt3threshv = P3l(P0, alpha)
#   temp = function(pt3){
#     gbmpdf(pt3, pt2, taub) * util2Acont(pt3)
#   }
#   gbmcdf(pt3threshv, pt2, taub) * util2Astop(P0) + integrate(temp, pt3threshv, Inf, abs.tol = 0)$value
#   }
#   integrate(Vectorize(temp0), alphalower, 1, abs.tol = 0)$value / (1-alphalower)
# }


## unitily of Alice at t_3 if continue, Alice gets 1 at t_3+taub if P_3 > P_3 lowerbound
util2Acontunc = function(pt3vs, alpha){utilunc(
  pt3vs*exp(mu*taub), taub, 1, 1, alpha
  )}

## utility of Alice at t_3 if withdraw, Alice gets P0 at t_3+taua+taueps
util2Astopunc = function(P0, alpha){utilunc(
  P0, taua+taueps, 0, 1, alpha
  )}

## expected utility of Alice at t_3 given t_2
util2Aunc = function(pt2, P0, alpha=alphalower){
  pt3threshv = P3l(P0, alpha)
  temp = function(pt3){
    gbmpdf(pt3, pt2, taub) * util2Acontunc(pt3, alpha)
  }
  gbmcdf(pt3threshv, pt2, taub) * util2Astopunc(P0, alpha) + integrate(temp, pt3threshv, Inf, abs.tol = 0)$value
}


## only calculate the boundary value
util1Acontunc = function(P0, alphalower, alphaB){
  
  pt2threshv = P2threshunc(P0, alphalower, alphaB)
  
  temp = function(pt2){
    gbmpdf(pt2, pt1, taua) * util2Aunc(pt2, P0, alpha=alphalower)
  }
  
  utilAifBwaiv = P0/exp(rs[1]*(2*taua+taub))
  
  if(length(pt2threshv)==0){
    # alphaB too small, Bob will never swap anyway.
    utilAifBwaiv
  }else{
    # Alice's utility at t3 if Bob continues, gives terribly wrong answer if omitting abs.tol
    utilt3 = integrate(Vectorize(temp), pt2threshv[1], pt2threshv[2], abs.tol = 0)$value
    probBobwaive = 1 - gbmcdf(pt2threshv[2], P0, taua) + gbmcdf(pt2threshv[1], P0, taua)
    
    utilt3 / exp(rs[1]*(taua+taub)) + probBobwaive*utilAifBwaiv
  }
}

# util1Acontunc(P0=1.2, 0, alphaB=0.5)
# util1Acontunc(P0=1.2, 0.9999999, alphaB=0.5)

startlessstopAunc = function(P0, alphalower){
  temp = function(alphaB){util1Acontunc(P0, alphalower, alphaB)}
  integrate(Vectorize(temp), 0, 1, abs.tol = 0)$value - P0
}

alphal = function(P0){
  temp = function(alphalower){
    startlessstopAunc(P0, alphalower)
  }
  uniroot(Vectorize(temp), c(0.00001, 0.99999))
}

```

```{r alphalower, include=F, eval=F}
datanumber = 11
P0s = seq(1.5, 3, length.out = datanumber)

alphals = rep(NA, datanumber)

# for (i in 1:datanumber){
#   try(
#     alphals[i] <- alphal(P0s[i])$root, silent = T
#   )
#   # if (startlessstopAunc(P0s[i], 0) >= 0){
#   #  alphals[i] = 0
#   # }else{
#   #   if (startlessstopAunc(P0s[i], 0) > 0){
#   #     alphals[i] = alphal(P0s[i])$root
#   #   }
#   # }
# }

# save(alphals, file = "alphals.rda")

load('alphals.rda')

par(mar = c(2,2,0,0), oma = c(1,1,0,0), mgp = c(1, 0, 0), cex.axis=.9, cex = 1.7, tck = -0.01)

plot(P0s, alphals, type = 'b', pch = 4, xlab='P0', ylab = 'lower bound of alpha^A')
abline(v = pt1, lty =2)
text(x=pt1, y =0, 'Price at t1')
```

```{r plots, include=F, eval=F}

for(P0 in c(1.5, 2, 2.5)){
  par(mar = c(2,2,2,0), oma = c(1,1,0,0), mgp = c(1, 0, 0), cex.axis=.9, cex = 1.7, tck = -0.01)
  pt3threshv = P3l(P0, alphas[1])
  
  pt3vs1 = seq(1e-10,pt3threshv,length.out = 200)
  pt3vs2 = seq(pt3threshv, 5,length.out = 200)
  
  pt3vs = c(pt3vs1, pt3vs2)
  
  plot(pt3vs, util2Acont(pt3vs), type = 'l', 
       xlab = 'Price at t3', ylab = "Alice's utility at t3", 
       col = 'chartreuse3', main = paste('P0 =', P0))
  
  opt2Av = util2Astop(P0)
  lines(pt3vs, rep(opt2Av, length(pt3vs)))
  
  points(pt3threshv, opt2Av, pch = '.', col = 'red', cex = 5)
  
  legend('topleft', lty = c(1,1,NA), 
         pch = c(NA, NA, '.'),
         pt.cex = 5,
         col = c('chartreuse3', 'black', 'red'), 
         legend = c('continue', 'withdraw', 'Price lower bound at t3'))
  
  # 
  # lines(pt3vs, c(
  # rep(opt2Av, length(pt3vs1)),
  # util2Acont(pt3vs2)
  # ), col = 'chartreuse3', cex = 2)
  
  
  pt2s = c(1, 2, 3)
  
  plot(pt3vs, gbmpdf(pt3vs, pt2s[1], taub), type = 'l', 
       xlab = 'Price at t3', 
       ylab = 'Density', lty = 2, main = paste('P0 =', P0))
  lines(pt3vs, gbmpdf(pt3vs, pt2s[2], taub), lty = 1)
  lines(pt3vs, gbmpdf(pt3vs, pt2s[3], taub), lty = 3)
  
  abline(v = pt3threshv, col = 'red')
  
  legend('topright', lty = c(2,1,3), 
         legend = pt2s,
         title = 'Price at t2')
  
  
  pt2vs = seq(1e-10,5,length.out = 200)
  
  pt2threshsv = P2thresh(P0)
  
  plot(pt2vs, pt2vs, type = 'l', 
       xlab = 'Price at t2', ylab = "Bob's utility at t2", main = paste('P0 =', P0))
  lines(pt2vs, utilBcont(pt2vs, P0), col = 'chartreuse3')
  points(pt2threshsv[1], pt2threshsv[1], pch = '.', col = 'red', cex = 5)
  points(pt2threshsv[2], pt2threshsv[2], pch = '.', col = 'blue', cex = 5)
  
  legend('topleft', lty = c(1,1, NA, NA), 
         pch = c(NA, NA, '.', '.'),
         pt.cex = 5,
         col = c('chartreuse3', 'black', 'red', 'blue'), 
         legend = c('continue', 'withdraw', 'Price lower bound at t2', 'Price upper bound at t2'))
  
  plot(pt2vs, gbmpdf(pt2vs, pt1, taua), type = 'l',
       xlab = 'Price at t2', ylab = 'Density', main = paste('P0 =', P0))
  abline(v = pt2threshsv, col = c('red', 'blue'))
}

# utilA0=c()
# for (P0 in P0s){
#   utilA0 = c(utilA0, util1Acont(P0))
# }

utilA0 = Vectorize(util1Acont)(P0s)

plot(c(0,max(P0s)),c(0,max(P0s)),type = 'l', 
       xlab = 'Swap price P0', ylab = "Alice's utility at t1")
lines(P0s, utilA0, col = 'chartreuse3')

p0boundsind = which(diff(P0s-utilA0 <0)!=0)
points(P0s[p0boundsind], P0s[p0boundsind], col = c('red','blue'), pch = '.', cex = 5)

abline(v = pt1, lty =2)
text(x=pt1, y =0, 'Price at t1')

legend('topleft', lty = c(1,1, NA, NA), 
         pch = c(NA, NA, '.', '.'),
         pt.cex = 5,
         col = c('chartreuse3', 'black', 'red', 'blue'), 
         legend = c('continue', 'withdraw', 'Swap price lower bound ', 'Swap price upper bound'))
```

```{r plots_col, include=F, eval=T}
# no need to use `plots` chunk anymore, since no collateral is a special case of with collateral

collat_list = list(c(0,0), c(0.02,0.02), c(0.5,0.5))
for(collat_index in 1:length(collat_list)){
  collat = collat_list[[collat_index]] # collaterals that Alice and Bob put in, respectively

for(P0 in c(1.5, 2, 2.5)){
  par(mar = c(2,2,2,0), oma = c(1,1,0,0), mgp = c(1, 0, 0), cex.axis=.9, cex = 1.7, tck = -0.01)
  pt3threshv = P3l_col(P0, alphas[1])
  
  pt3vs1 = seq(1e-10,pt3threshv,length.out = 200)
  pt3vs2 = seq(pt3threshv, 5,length.out = 200)
  
  pt3vs = c(pt3vs1, pt3vs2)
  
  plot(pt3vs, util2Acont_col(pt3vs), type = 'l', 
       xlab = 'Price at t3', ylab = "Alice's utility at t3", 
       col = 'chartreuse3', main = paste('P0 =', P0))
  
  opt2Av = util2Astop(P0)
  lines(pt3vs, rep(opt2Av, length(pt3vs)))
  
  points(pt3threshv, opt2Av, pch = '.', col = 'red', cex = 5)
  
  legend('topleft', lty = c(1,1,NA), 
         pch = c(NA, NA, '.'),
         pt.cex = 5,
         col = c('chartreuse3', 'black', 'red'), 
         legend = c('continue', 'withdraw', 'Price lower bound at t3'))
  
  
  pt2s = c(1, 2, 3)
  
  plot(pt3vs, gbmpdf(pt3vs, pt2s[1], taub), type = 'l', 
       xlab = 'Price at t3', 
       ylab = 'Density', lty = 2, main = paste('P0 =', P0))
  lines(pt3vs, gbmpdf(pt3vs, pt2s[2], taub), lty = 1)
  lines(pt3vs, gbmpdf(pt3vs, pt2s[3], taub), lty = 3)
  
  abline(v = pt3threshv, col = 'red')
  
  legend('topright', lty = c(2,1,3), 
         legend = pt2s,
         title = 'Price at t2')
  
  
  pt2vs = seq(1e-10,5,length.out = 200)
  
  pt2threshsv = P2thresh_col(P0)
  
  plot(pt2vs, pt2vs, type = 'l', ylim = c(0,3), xlim =c(0,3),
       xlab = 'Price at t2', ylab = "Bob's utility at t2", main = paste('P0 =', P0))
  lines(pt2vs, utilBcont_col(pt2vs, P0), col = 'chartreuse3')
  points(pt2threshsv,pt2threshsv, pch = '.', col = c('blue','red'), cex = 5)
  # points(pt2threshsv[2], pt2threshsv[2], pch = '.', col = 'blue', cex = 5)
  
  legend('topleft', lty = c(1,1, NA, NA), 
         pch = c(NA, NA, '.', '.'),
         pt.cex = 5,
         col = c('chartreuse3', 'black', 'red', 'blue'), 
         legend = c('continue', 'withdraw', 'Price lower bounds at t2', 'Price upper bounds at t2'))
  
  plot(pt2vs, gbmpdf(pt2vs, pt1, taua), type = 'l',
       xlab = 'Price at t2', ylab = 'Density', main = paste('P0 =', P0))
  abline(v = pt2threshsv, col = c('red', 'blue'))
}

# utilA0=c()
# for (P0 in P0s){
#   utilA0 = c(utilA0, util1Acont(P0))
# }

utilA0 = Vectorize(util1Acont_col)(P0s)

plot(c(0,max(P0s)),c(0,max(P0s)) + collat[1],type = 'l', ylim = c(0,3), xlim =c(0,3),
       xlab = 'Swap price P0', ylab = "Alice's utility at t1")
lines(P0s, utilA0, col = 'chartreuse3')

p0boundsind = which(diff(P0s + collat[1] - utilA0 <0)!=0)
points(P0s[p0boundsind], P0s[p0boundsind] + collat[1], col = c('red','blue'), pch = '.', cex = 5)
text(x=pt1, y =0, 'Price at t1')

legend('topleft', lty = c(1,1, NA, NA), 
         pch = c(NA, NA, '.', '.'),
         pt.cex = 5,
         col = c('chartreuse3', 'black', 'red', 'blue'), 
         legend = c('continue', 'withdraw', 'Swap price lower bound ', 'Swap price upper bound')
       , cex = 0.6)



# P0s_valid = seq(P0s[p0boundsind][1], P0s[p0boundsind][2], length.out = 99)
utilB0 = Vectorize(util1Bcont_col)(P0s)

plot(P0s, utilB0, col = 'chartreuse3',type = 'l', ylim = c(0,3), xlim =c(0,3),
       xlab = 'Swap price P0', ylab = "Bob's utility at t1")

abline(h = 1+collat[2], lty =1)
abline(v = pt1, lty =2)
abline(v = P0s[p0boundsind], lty =2, col = c('red','blue'))

p0boundsind_B = which(diff(1 + collat[2] - utilB0 <0)!=0)

if (length(p0boundsind_B)>0){
points(P0s[p0boundsind_B], 1 + collat[2], col = c('orange'), pch = '.', cex = 5)
}

text(x=pt1, y =0, 'Price at t1')
legend('topleft', lty = c(1,1,2,2, NA), 
         pch = c(NA, NA,NA, NA, '.'),
         pt.cex = 5,
         col = c('chartreuse3', 'black', 'red', 'blue', 'orange'), 
         legend = c('continue', 'withdraw', 
                    'Swap price lower bound for Alice', 'Swap price upper bound for Alice',
                    'Swap price lower bound for Bob' 
                    ), cex = 0.6)
}
```

```{r sigmas_coll, include=T, eval = F}
taua = 3
taub = 4

sigmas = c(0.06, 0.09, 0.12)

utilA0s = list()
validp0s = list()
sucrates = list()

collat_list = list(c(0,0), c(0.02,0.02), c(0.5,0.5))
for(collat_index in 1:length(collat_list)){
  collat = collat_list[[collat_index]] # collaterals that Alice and Bob put in, respectively
for (i in 1:3){
sigma = sigmas[i]
utilA0 = Vectorize(util1Acont_col)(P0s)
# for (x in P0s){
#   print(util1Acont_col(x))
#   print(x)
# }

utilA0s[[i]] = utilA0
p0boundsind = which(diff(P0s+collat[1] - utilA0 <0)!=0)

validp0 = seq(P0s[p0boundsind[1]], P0s[p0boundsind[2]], length.out = 999)
validp0s[[i]] = validp0
sucrates[[i]] = Vectorize(sucrate_col)(validp0)
}

# for (x in validp0){
#   print(sucrate_col(x))
#   print(x)
# }

par(mar = c(2,2,0,0), oma = c(1,1,0,0), mgp = c(1, 0, 0), cex.axis=.9, cex = 1.7, tck = -0.01)

plot(c(0,max(P0s)),c(0,max(P0s))+ collat[1],type = 'l', 
       xlab = 'Swap price P0', ylab = "Alice's utility at t1")

# abline(h = collat[1], col = 'orange')
ltys = c(2,1,3)
for (i in 1:3){
lines(P0s, utilA0s[[i]], col = 'chartreuse3', lty = ltys[i])
points(validp0s[[i]] %>% range, validp0s[[i]] %>% range + collat[1], col = c('red','blue'), pch = '.', cex = 5)
}

abline(v = pt1, lty =2)
text(x=pt1, y = 0, 'Price at t1')

legend('topleft', lty = ltys, 
         col = c('chartreuse3'), 
         legend = sigmas,
       title = "sigma")


plot(NULL, xlim = c(0,max(P0s)),ylim = c(0,1),
       xlab = 'Swap price P0', ylab = "Success rate")

# sigmas = c(0.06, 0.1, 0.14)
ltys = c(2,1,3)

for (i in 1:3){
lines(validp0s[[i]], sucrates[[i]], col = 'chartreuse3', lty = ltys[i])
}

legend('topleft', lty = ltys, 
         col = c('chartreuse3'), 
         legend = sigmas,
       title = "sigma")
}
```

```{r tauas, include=F, eval = F}
sigma = 0.1

par(mar = c(2,2,0,0), oma = c(1,1,0,0), mgp = c(1, 0, 0), cex.axis=.9, cex = 1.7, tck = -0.01)

plot(c(0,max(P0s)),c(0,max(P0s)),type = 'l', 
       xlab = 'Swap price P0', ylab = "Alice's utility at t1")

tauas = c(0.5, 3, 5.5)
ltys = c(2,1,3)
for (i in 1:3){
taua = tauas[i]
utilA0 = Vectorize(util1Acont)(P0s)
lines(P0s, utilA0, col = 'chartreuse3', lty = ltys[i])

p0boundsind = which(diff(P0s-utilA0 <0)!=0)
points(P0s[p0boundsind], P0s[p0boundsind], col = c('red','blue'), pch = '.', cex = 5)

}


abline(v = pt1, lty =2)
text(x=pt1, y = 0, 'Price at t1')

legend('topleft', lty = ltys, 
         col = c('chartreuse3'), 
         legend = tauas,
       title = "tau_a")
```

```{r taubs, include=F, eval = F}
sigma = 0.1

par(mar = c(2,2,0,0), oma = c(1,1,0,0), mgp = c(1, 0, 0), cex.axis=.9, cex = 1.7, tck = -0.01)

plot(c(0,max(P0s)),c(0,max(P0s)),type = 'l', 
       xlab = 'Swap price P0', ylab = "Alice's utility at t1")

taubs = c(0.5, 4, 7.5)
ltys = c(2,1,3)
for (i in 1:3){
taub = taubs[i]
utilA0 = Vectorize(util1Acont)(P0s)
lines(P0s, utilA0, col = 'chartreuse3', lty = ltys[i])

p0boundsind = which(diff(P0s-utilA0 <0)!=0)
points(P0s[p0boundsind], P0s[p0boundsind], col = c('red','blue'), pch = '.', cex = 5)

}


abline(v = pt1, lty =2)
text(x=pt1, y = 0, 'Price at t1')

legend('topleft', lty = ltys, 
         col = c('chartreuse3'), 
         legend = taubs,
       title = "tau_b")
```

```{r sigmas, include=F, eval = F}
taua = 3
taub = 4

sigmas = c(0.06, 0.9, 0.12)

utilA0s = list()
validp0s = list()
sucrates = list()

for (i in 1:3){
sigma = sigmas[i]
utilA0 = Vectorize(util1Acont)(P0s)
utilA0s[[i]] = utilA0
p0boundsind = which(diff(P0s-utilA0 <0)!=0)

validp0 = seq(P0s[p0boundsind[1]], P0s[p0boundsind[2]], length.out = 999)
validp0s[[i]] = validp0
sucrates[[i]] = Vectorize(sucrate)(validp0)
}


par(mar = c(2,2,0,0), oma = c(1,1,0,0), mgp = c(1, 0, 0), cex.axis=.9, cex = 1.7, tck = -0.01)

plot(c(0,max(P0s)),c(0,max(P0s)),type = 'l', 
       xlab = 'Swap price P0', ylab = "Alice's utility at t1")


ltys = c(2,1,3)
for (i in 1:3){
lines(P0s, utilA0s[[i]], col = 'chartreuse3', lty = ltys[i])
points(validp0s[[i]] %>% range, validp0s[[i]] %>% range, col = c('red','blue'), pch = '.', cex = 5)
}

abline(v = pt1, lty =2)
text(x=pt1, y = 0, 'Price at t1')

legend('topleft', lty = ltys, 
         col = c('chartreuse3'), 
         legend = sigmas,
       title = "sigma")


plot(NULL, xlim = c(0,max(P0s)),ylim = c(0,1),
       xlab = 'Swap price P0', ylab = "Success rate")

# sigmas = c(0.06, 0.1, 0.14)
ltys = c(2,1,3)

for (i in 1:3){
lines(validp0s[[i]], sucrates[[i]], col = 'chartreuse3', lty = ltys[i])
}

legend('topleft', lty = ltys, 
         col = c('chartreuse3'), 
         legend = sigmas,
       title = "sigma")
```

```{r alphas, include=F, eval=F}
sigma = 0.1

par(mar = c(2,2,0,0), oma = c(1,1,0,0), mgp = c(1, 0, 0), cex.axis=.9, cex = 1.7, tck = -0.01)

plot(c(0,max(P0s)),c(0,max(P0s)),type = 'l', 
       xlab = 'Swap price P0', ylab = "Alice's utility at t1")

a1s = c(0.1, 0.2, 0.3)
ltys = c(2,1,3)
for (i in 1:3){
alphas[1] = a1s[i]
utilA0 = Vectorize(util1Acont)(P0s)
lines(P0s, utilA0, col = 'chartreuse3', lty = ltys[i])

p0boundsind = which(diff(P0s-utilA0 <0)!=0)
points(P0s[p0boundsind], P0s[p0boundsind], col = c('red','blue'), pch = '.', cex = 5)

}


abline(v = pt1, lty =2)
text(x=pt1, y =0, 'Price at t1')

legend('topleft', lty = ltys, 
         col = c('chartreuse3'), 
         legend = a1s,
       title = "Alice's alpha")
```

```{r rs, include=F, eval=F}
alphas[1] = 0.2

par(mar = c(2,2,0,0), oma = c(1,1,0,0), mgp = c(1, 0, 0), cex.axis=.9, cex = 1.7, tck = -0.01)

plot(c(0,max(P0s)),c(0,max(P0s)),type = 'l', 
       xlab = 'Swap price P0', ylab = "Alice's utility at t1")

r1s = c(0.001, 0.01, 0.05)
ltys = c(2,1,3)
for (i in 1:3){
rs[1] = r1s[i]
utilA0 = Vectorize(util1Acont)(P0s)
lines(P0s, utilA0, col = 'chartreuse3', lty = ltys[i])

p0boundsind = which(diff(P0s-utilA0 <0)!=0)
points(P0s[p0boundsind], P0s[p0boundsind], col = c('red','blue'), pch = '.', cex = 5)

}


abline(v = pt1, lty =2)
text(x=pt1, y =0, 'Price at t1')

legend('topleft', lty = ltys, 
         col = c('chartreuse3'), 
         legend = a1s,
       title = "Alice's r")
```